name: flutter_feature_gen
description: A Dart CLI tool to generate clean architecture Flutter features.
version: 1.0.2
repository: https://github.com/jamal-and/flutter_feature_gen

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  
executables:
  flutter_feature_gen: main
  
example: example/main.dart

